"""make room capacity nullable

Revision ID: 63111d95d4d4
Revises: 96c82805be0d
Create Date: 2026-09-10 15:58:21.350662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63111d95d4d4'
down_revision: Union[str, Sequence[str], None] = '96c82805be0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
