"""add unique constraint on schedule_version semester and version_number

Revision ID: b049ab23b45e
Revises: 02850681b45e
Create Date: 2026-09-10 20:16:09.114603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b049ab23b45e'
down_revision: Union[str, Sequence[str], None] = '02850681b45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_schedule_version_semester_number', 'schedule_versions', ['semester_id', 'version_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_schedule_version_semester_number', 'schedule_versions', type_='unique')
    # ### end Alembic commands ###
