"""make time_slot start_time and end_time nullable

Revision ID: bfc4d1048463
Revises: 63111d95d4d4
Create Date: 2026-09-10 16:03:15.354153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfc4d1048463'
down_revision: Union[str, Sequence[str], None] = '63111d95d4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_slots', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('time_slots', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_slots', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('time_slots', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###
