"""add class_subject_requirement

Revision ID: d3ba9babdb90
Revises: cbbf4d13d8bb
Create Date: 2026-09-10 15:15:14.086791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ba9babdb90'
down_revision: Union[str, Sequence[str], None] = 'cbbf4d13d8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_subject_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('weekly_periods', sa.Integer(), nullable=False),
    sa.Column('required_teacher_id', sa.Integer(), nullable=True),
    sa.Column('required_room_type', sa.String(length=100), nullable=True),
    sa.Column('consecutive_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['required_teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'class_id', 'subject_id', name='uq_class_subject_requirement')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_subject_requirements')
    # ### end Alembic commands ###
