"""add time_slot label

Revision ID: f8314700cad8
Revises: 6d3e68b11338
Create Date: 2026-09-14 16:09:15.864955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8314700cad8'
down_revision: Union[str, Sequence[str], None] = '6d3e68b11338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('label', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_slots', 'label')
    # ### end Alembic commands ###
